version: 2
jobs:
  test:
    working_directory: ~/kenobi
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout

      - restore_cache:
          key: main-dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: main-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: npm run build
      - run: npm run test

workflows:
  version: 2
  default:
    jobs:
      - test